[package]
name = "patternfly-yew-quickstart"
version = "0.4.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
description = "A quickstart project for using PatternFly with Yew Stack"
repository = "https://github.com/ctron/patternfly-yew-quickstart"

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
gloo-utils = "0.1"
log = "0.4"
patternfly-yew = { version = "0.4.0-alpha.3", features = ["icons-fab", "tree"] }
strum = "0.24"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-nested-router = "0.2"

[patch.crates-io]
#patternfly-yew = { path = "../patternfly-yew" }
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "dbe0cab145ca681fc23c6c8466eb975cbccc2e4d" } # FIXME: awaiting release
#yew-nested-router = { path = "../yew-nested-router" }
